export type ChemicalPhase = "solid" | "liquid" | "gas";
export type ChemicalCategory =
  | "acid"
  | "base"
  | "salt"
  | "oxidizer"
  | "metal"
  | "solvent"
  | "catalyst";

export type HazardCode =
  | "corrosive"
  | "toxic"
  | "oxidizer"
  | "irritant"
  | "environment"
  | "flammable"
  | "gas";

export interface ChemicalModel {
  /** Scientific appearance data, intentionally independent from UI theme tokens. */
  albedo: string;
  transmission: number;
  roughness: number;
  metalness: number;
  particleShape: "crystal" | "powder" | "pellet" | "liquid" | "metal";
}

export interface ChemicalSpec {
  id: string;
  name: string;
  formula: string;
  category: ChemicalCategory;
  phase: ChemicalPhase;
  form: string;
  molarMass: number;
  density: string;
  meltingPoint: string;
  boilingPoint: string;
  appearance: string;
  solubility: string;
  concentrationM?: number;
  purity: number;
  defaultUnit: "g" | "mL";
  hazards: HazardCode[];
  handling: string;
  realWorld: string;
  model: ChemicalModel;
}

export const CHEMISTRY_CATALOGUE: ChemicalSpec[] = [
  {
    id: "h2o",
    name: "Nước cất",
    formula: "H₂O",
    category: "solvent",
    phase: "liquid",
    form: "Chất lỏng tinh khiết",
    molarMass: 18.015,
    density: "0,997 g/mL · 25 °C",
    meltingPoint: "0 °C",
    boilingPoint: "100 °C · 1 atm",
    appearance: "Không màu, trong suốt",
    solubility: "Dung môi phân cực",
    purity: 1,
    defaultUnit: "mL",
    hazards: [],
    handling: "Giữ dụng cụ sạch để tránh nhiễm ion.",
    realWorld: "Dung môi, làm mát và pha loãng dung dịch.",
    model: { albedo: "#b8e7f4", transmission: 0.72, roughness: 0.08, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "nacl",
    name: "Natri clorua",
    formula: "NaCl",
    category: "salt",
    phase: "solid",
    form: "Tinh thể ion khan",
    molarMass: 58.44,
    density: "2,165 g/cm³",
    meltingPoint: "801 °C",
    boilingPoint: "1.465 °C",
    appearance: "Tinh thể trắng, không mùi",
    solubility: "35,9 g/100 mL H₂O · 25 °C",
    purity: 0.99,
    defaultUnit: "g",
    hazards: [],
    handling: "Tránh làm nhiễm bẩn lọ chất chuẩn.",
    realWorld: "Thực phẩm, dung dịch sinh lý và điện phân chlor-alkali.",
    model: { albedo: "#edf2f4", transmission: 0.05, roughness: 0.62, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "hcl",
    name: "Axit clohidric",
    formula: "HCl (aq)",
    category: "acid",
    phase: "liquid",
    form: "Dung dịch 1,0 mol/L",
    molarMass: 36.46,
    density: "Xấp xỉ 1,02 g/mL",
    meltingPoint: "Phụ thuộc nồng độ",
    boilingPoint: "Phụ thuộc nồng độ",
    appearance: "Không màu; có thể bốc khói ở nồng độ cao",
    solubility: "Trộn lẫn hoàn toàn với nước",
    concentrationM: 1,
    purity: 1,
    defaultUnit: "mL",
    hazards: ["corrosive", "irritant"],
    handling: "Dùng kính, găng và tủ hút khi có nguy cơ phát sinh khí.",
    realWorld: "Tẩy gỉ, điều chỉnh pH và tổng hợp muối clorua.",
    model: { albedo: "#d9eef0", transmission: 0.78, roughness: 0.1, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "naoh",
    name: "Natri hiđroxit",
    formula: "NaOH",
    category: "base",
    phase: "solid",
    form: "Viên rắn khan",
    molarMass: 40,
    density: "2,13 g/cm³",
    meltingPoint: "318 °C",
    boilingPoint: "1.388 °C",
    appearance: "Viên trắng, hút ẩm mạnh",
    solubility: "Tan mạnh trong nước, tỏa nhiệt",
    purity: 0.98,
    defaultUnit: "g",
    hazards: ["corrosive"],
    handling: "Không chạm tay; thêm từ từ vào nước, không làm ngược lại.",
    realWorld: "Xà phòng, giấy, xử lý nước và điều chỉnh pH.",
    model: { albedo: "#f0f1ee", transmission: 0.02, roughness: 0.54, metalness: 0, particleShape: "pellet" },
  },
  {
    id: "cuso4",
    name: "Đồng(II) sunfat ngậm nước",
    formula: "CuSO₄·5H₂O",
    category: "salt",
    phase: "solid",
    form: "Tinh thể pentahiđrat",
    molarMass: 249.68,
    density: "2,28 g/cm³",
    meltingPoint: "Mất nước từ khoảng 110 °C",
    boilingPoint: "Phân hủy trước khi sôi",
    appearance: "Tinh thể xanh lam",
    solubility: "Khoảng 32 g/100 mL H₂O · 20 °C",
    purity: 0.98,
    defaultUnit: "g",
    hazards: ["irritant", "environment"],
    handling: "Không thải dung dịch chứa đồng xuống cống.",
    realWorld: "Mạ đồng, thuốc thử và kiểm soát nấm trong nông nghiệp.",
    model: { albedo: "#2387c9", transmission: 0.08, roughness: 0.32, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "h2so4",
    name: "Axit sunfuric",
    formula: "H₂SO₄",
    category: "acid",
    phase: "liquid",
    form: "Dung dịch 1,0 mol/L trong mô phỏng",
    molarMass: 98.08,
    density: "1,84 g/mL · dạng 98%",
    meltingPoint: "10,3 °C · dạng tinh khiết",
    boilingPoint: "Khoảng 337 °C, có phân hủy",
    appearance: "Không màu, sánh",
    solubility: "Trộn với nước và tỏa nhiệt rất mạnh",
    concentrationM: 1,
    purity: 1,
    defaultUnit: "mL",
    hazards: ["corrosive"],
    handling: "Luôn thêm axit vào nước, làm mát và che chắn.",
    realWorld: "Ắc quy, phân bón và nhiều quy trình công nghiệp.",
    model: { albedo: "#dfe9e7", transmission: 0.69, roughness: 0.13, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "kmno4",
    name: "Kali pemanganat",
    formula: "KMnO₄",
    category: "oxidizer",
    phase: "solid",
    form: "Tinh thể",
    molarMass: 158.03,
    density: "2,70 g/cm³",
    meltingPoint: "Phân hủy khoảng 240 °C",
    boilingPoint: "Không sôi; phân hủy",
    appearance: "Tinh thể tím đen; dung dịch tím",
    solubility: "Khoảng 6,4 g/100 mL H₂O · 20 °C",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["oxidizer", "corrosive", "environment"],
    handling: "Cách ly chất hữu cơ và chất khử.",
    realWorld: "Thuốc thử oxi hóa và xử lý nước có kiểm soát.",
    model: { albedo: "#4e176f", transmission: 0.03, roughness: 0.38, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "bacl2",
    name: "Bari clorua",
    formula: "BaCl₂·2H₂O",
    category: "salt",
    phase: "solid",
    form: "Tinh thể đihiđrat",
    molarMass: 244.26,
    density: "Khoảng 3,10 g/cm³",
    meltingPoint: "Mất nước khi gia nhiệt",
    boilingPoint: "Phân hủy ở nhiệt độ cao",
    appearance: "Tinh thể trắng",
    solubility: "Tan trong nước",
    purity: 0.98,
    defaultUnit: "g",
    hazards: ["toxic"],
    handling: "Không để tiếp xúc da hoặc đường tiêu hóa; thu gom chất thải bari.",
    realWorld: "Thuốc thử định tính ion sunfat.",
    model: { albedo: "#e9ebe5", transmission: 0.04, roughness: 0.52, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "agno3",
    name: "Bạc nitrat",
    formula: "AgNO₃",
    category: "salt",
    phase: "solid",
    form: "Tinh thể",
    molarMass: 169.87,
    density: "4,35 g/cm³",
    meltingPoint: "212 °C",
    boilingPoint: "Phân hủy khi đun mạnh",
    appearance: "Tinh thể không màu đến trắng",
    solubility: "Tan rất tốt trong nước",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["corrosive", "oxidizer", "environment"],
    handling: "Tránh ánh sáng và tiếp xúc da; thu hồi chất thải bạc.",
    realWorld: "Phân tích halide, mạ bạc và tổng hợp muối bạc.",
    model: { albedo: "#e9ece8", transmission: 0.12, roughness: 0.31, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "ki",
    name: "Kali iodua",
    formula: "KI",
    category: "salt",
    phase: "solid",
    form: "Tinh thể",
    molarMass: 166,
    density: "3,12 g/cm³",
    meltingPoint: "681 °C",
    boilingPoint: "1.330 °C",
    appearance: "Tinh thể trắng; có thể vàng nhẹ khi oxi hóa",
    solubility: "Tan rất tốt trong nước",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["irritant"],
    handling: "Đậy kín, tránh ẩm và chất oxi hóa mạnh.",
    realWorld: "Thuốc thử iodide và bổ sung iod theo chỉ định.",
    model: { albedo: "#eae9df", transmission: 0.05, roughness: 0.5, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "pbno3",
    name: "Chì(II) nitrat",
    formula: "Pb(NO₃)₂",
    category: "salt",
    phase: "solid",
    form: "Tinh thể",
    molarMass: 331.21,
    density: "4,53 g/cm³",
    meltingPoint: "Phân hủy khoảng 470 °C",
    boilingPoint: "Không sôi; phân hủy",
    appearance: "Tinh thể trắng",
    solubility: "Tan trong nước",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["toxic", "oxidizer", "environment"],
    handling: "Chỉ thao tác trong hệ kín; chất thải chì phải thu gom riêng.",
    realWorld: "Thuốc thử vô cơ chuyên dụng; không dùng trong sinh hoạt.",
    model: { albedo: "#e6e8e4", transmission: 0.03, roughness: 0.59, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "fecl3",
    name: "Sắt(III) clorua",
    formula: "FeCl₃·6H₂O",
    category: "salt",
    phase: "solid",
    form: "Tinh thể ngậm nước",
    molarMass: 270.3,
    density: "Khoảng 1,82 g/cm³",
    meltingPoint: "Khoảng 37 °C",
    boilingPoint: "Phân hủy khi gia nhiệt",
    appearance: "Tinh thể vàng nâu; dung dịch vàng nâu",
    solubility: "Tan mạnh trong nước",
    purity: 0.98,
    defaultUnit: "g",
    hazards: ["corrosive", "irritant"],
    handling: "Tránh ẩm, bảo vệ mắt và da.",
    realWorld: "Khắc mạch đồng, xử lý nước và thuốc thử.",
    model: { albedo: "#a55d20", transmission: 0.04, roughness: 0.47, metalness: 0, particleShape: "crystal" },
  },
  {
    id: "nh3",
    name: "Dung dịch amoniac",
    formula: "NH₃ (aq)",
    category: "base",
    phase: "liquid",
    form: "Dung dịch 1,0 mol/L",
    molarMass: 17.031,
    density: "Phụ thuộc nồng độ",
    meltingPoint: "Phụ thuộc nồng độ",
    boilingPoint: "Phụ thuộc nồng độ",
    appearance: "Không màu, mùi khai mạnh",
    solubility: "Trộn với nước",
    concentrationM: 1,
    purity: 1,
    defaultUnit: "mL",
    hazards: ["corrosive", "gas", "environment"],
    handling: "Chỉ mở trong tủ hút; tránh hít hơi.",
    realWorld: "Điều chỉnh pH, sản xuất phân bón và thuốc thử tạo phức.",
    model: { albedo: "#d9ecea", transmission: 0.76, roughness: 0.09, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "h2o2",
    name: "Hiđro peoxit",
    formula: "H₂O₂",
    category: "oxidizer",
    phase: "liquid",
    form: "Dung dịch 3%",
    molarMass: 34.015,
    density: "Khoảng 1,01 g/mL · dung dịch 3%",
    meltingPoint: "Phụ thuộc nồng độ",
    boilingPoint: "Phụ thuộc nồng độ; phân hủy",
    appearance: "Không màu",
    solubility: "Trộn lẫn với nước",
    concentrationM: 0.88,
    purity: 1,
    defaultUnit: "mL",
    hazards: ["oxidizer", "irritant"],
    handling: "Tránh ánh sáng, nhiệt và tạp chất kim loại.",
    realWorld: "Tẩy trắng và oxi hóa ở nồng độ được kiểm soát.",
    model: { albedo: "#cfe8ea", transmission: 0.78, roughness: 0.08, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "ch3cooh",
    name: "Axit axetic",
    formula: "CH₃COOH",
    category: "acid",
    phase: "liquid",
    form: "Dung dịch 1,0 mol/L",
    molarMass: 60.052,
    density: "1,049 g/mL · dạng băng",
    meltingPoint: "16,6 °C · dạng tinh khiết",
    boilingPoint: "118,1 °C · dạng tinh khiết",
    appearance: "Không màu, mùi giấm",
    solubility: "Trộn lẫn với nước",
    concentrationM: 1,
    purity: 1,
    defaultUnit: "mL",
    hazards: ["corrosive", "flammable"],
    handling: "Tránh nguồn lửa và hơi đậm đặc.",
    realWorld: "Thực phẩm, tổng hợp acetate và điều chỉnh pH.",
    model: { albedo: "#dcebe7", transmission: 0.74, roughness: 0.1, metalness: 0, particleShape: "liquid" },
  },
  {
    id: "caco3",
    name: "Canxi cacbonat",
    formula: "CaCO₃",
    category: "salt",
    phase: "solid",
    form: "Bột mịn",
    molarMass: 100.086,
    density: "2,71 g/cm³ · calcit",
    meltingPoint: "Phân hủy khoảng 825 °C",
    boilingPoint: "Không sôi; phân hủy",
    appearance: "Bột trắng",
    solubility: "Rất ít tan trong nước",
    purity: 0.98,
    defaultUnit: "g",
    hazards: ["irritant"],
    handling: "Tránh tạo bụi hô hấp.",
    realWorld: "Xi măng, đá vôi, chất độn và xử lý axit.",
    model: { albedo: "#e5e5dc", transmission: 0.01, roughness: 0.78, metalness: 0, particleShape: "powder" },
  },
  {
    id: "zn",
    name: "Kẽm",
    formula: "Zn",
    category: "metal",
    phase: "solid",
    form: "Hạt kim loại",
    molarMass: 65.38,
    density: "7,14 g/cm³",
    meltingPoint: "419,5 °C",
    boilingPoint: "907 °C",
    appearance: "Kim loại xám bạc",
    solubility: "Không tan trong nước; phản ứng với axit",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["environment"],
    handling: "Tránh bụi kẽm và nguồn lửa khi có hiđro.",
    realWorld: "Mạ chống ăn mòn, hợp kim và pin.",
    model: { albedo: "#8b9391", transmission: 0, roughness: 0.28, metalness: 0.88, particleShape: "metal" },
  },
  {
    id: "cu",
    name: "Đồng",
    formula: "Cu",
    category: "metal",
    phase: "solid",
    form: "Dây kim loại",
    molarMass: 63.546,
    density: "8,96 g/cm³",
    meltingPoint: "1.084,6 °C",
    boilingPoint: "2.562 °C",
    appearance: "Kim loại đỏ cam",
    solubility: "Không tan trong nước",
    purity: 0.995,
    defaultUnit: "g",
    hazards: ["environment"],
    handling: "Thu hồi dung dịch muối đồng sau thí nghiệm.",
    realWorld: "Dây dẫn điện, hợp kim và bề mặt trao đổi nhiệt.",
    model: { albedo: "#a95f36", transmission: 0, roughness: 0.24, metalness: 0.92, particleShape: "metal" },
  },
  {
    id: "mg",
    name: "Magie",
    formula: "Mg",
    category: "metal",
    phase: "solid",
    form: "Dải kim loại",
    molarMass: 24.305,
    density: "1,738 g/cm³",
    meltingPoint: "650 °C",
    boilingPoint: "1.091 °C",
    appearance: "Kim loại trắng bạc",
    solubility: "Không tan trong nước lạnh; phản ứng với axit",
    purity: 0.99,
    defaultUnit: "g",
    hazards: ["flammable"],
    handling: "Không đốt dải magie ngoài che chắn chuyên dụng.",
    realWorld: "Hợp kim nhẹ, pháo sáng công nghiệp và chất khử.",
    model: { albedo: "#b9c0be", transmission: 0, roughness: 0.2, metalness: 0.94, particleShape: "metal" },
  },
  {
    id: "mno2",
    name: "Mangan(IV) oxit",
    formula: "MnO₂",
    category: "catalyst",
    phase: "solid",
    form: "Bột",
    molarMass: 86.936,
    density: "Khoảng 5,03 g/cm³",
    meltingPoint: "Phân hủy khoảng 535 °C",
    boilingPoint: "Không sôi; phân hủy",
    appearance: "Bột nâu đen",
    solubility: "Không tan trong nước",
    purity: 0.95,
    defaultUnit: "g",
    hazards: ["irritant"],
    handling: "Tránh hít bụi; dùng lượng nhỏ như chất xúc tác.",
    realWorld: "Pin khô, chất xúc tác và vật liệu gốm.",
    model: { albedo: "#252724", transmission: 0, roughness: 0.83, metalness: 0.08, particleShape: "powder" },
  },
];

export const CHEMICAL_BY_ID = Object.fromEntries(
  CHEMISTRY_CATALOGUE.map((chemical) => [chemical.id, chemical]),
) as Record<string, ChemicalSpec>;

export const HAZARD_LABELS: Record<HazardCode, string> = {
  corrosive: "Ăn mòn",
  toxic: "Độc",
  oxidizer: "Oxi hóa",
  irritant: "Kích ứng",
  environment: "Hại môi trường",
  flammable: "Dễ cháy",
  gas: "Hơi độc/kích ứng",
};
