using System.Collections.Generic;

namespace ChemistryLab.Desktop
{
    public static class ExtendedChemistryData
    {
        public static IEnumerable<ChemicalDefinition> BuildChemicals()
        {
            return new[]
            {
                C("nitric-acid", "Axit nitric", "HNO₃", ChemicalPhase.Liquid, ChemicalModelKind.Liquid,
                    63.012, "1,51 g/mL · nguyên chất", "−42 °C", "83 °C",
                    "Chất lỏng không màu, có thể ngả vàng do NO₂", "Trộn lẫn hoàn toàn với nước",
                    "Ăn mòn và oxi hóa mạnh; có thể sinh hơi NOₓ độc",
                    "Chỉ thao tác trong tủ hút; tránh chất hữu cơ và chất khử", "Điều chế muối nitrat và phản ứng oxi hóa",
                    "#E9E2C7", 0f, 0.82f, true),
                C("phosphoric-acid", "Axit photphoric", "H₃PO₄", ChemicalPhase.Liquid, ChemicalModelKind.Liquid,
                    97.994, "1,685 g/mL · dung dịch 85%", "42,4 °C · nguyên chất", "Phân hủy khoảng 213 °C",
                    "Chất lỏng sánh, không màu", "Trộn lẫn với nước",
                    "Ăn mòn; ít bay hơi hơn HCl và HNO₃", "Đeo kính và găng, pha loãng từ từ", "Tạo muối photphat và dung dịch đệm",
                    "#E8E1CB", 0f, 0.78f, true),
                C("potassium-hydroxide", "Kali hiđroxit", "KOH", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    56.105, "2,04 g/cm³", "360 °C", "1.327 °C",
                    "Viên trắng, hút ẩm và hút CO₂ mạnh", "Tan rất nhiều trong nước, tỏa nhiệt",
                    "Ăn mòn mạnh; gây bỏng sâu", "Đậy kín, tránh ẩm; luôn thêm chất rắn từ từ vào nước", "Bazơ mạnh và điều chế muối kali",
                    "#ECEBE4", 0f, 0.37f, false),
                C("calcium-hydroxide", "Canxi hiđroxit", "Ca(OH)₂", ChemicalPhase.Solid, ChemicalModelKind.Powder,
                    74.093, "2,21 g/cm³", "Phân hủy khoảng 580 °C", "Phân hủy",
                    "Bột trắng", "Ít tan: khoảng 0,17 g/100 mL H₂O · 20 °C",
                    "Bazơ ăn mòn; bụi gây kích ứng", "Tránh tạo bụi, dùng kính và găng", "Nước vôi trong, nhận biết CO₂ và xử lý axit",
                    "#E9E7DF", 0f, 0.25f, false),
                C("barium-hydroxide", "Bari hiđroxit", "Ba(OH)₂", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    171.342, "Khoảng 3,74 g/cm³", "Khoảng 408 °C · phân hủy", "Phân hủy",
                    "Tinh thể trắng", "Tan trong nước, độ tan tăng khi nóng",
                    "Ăn mòn và độc do ion Ba²⁺ tan", "Chỉ dùng trong khay độc chất; thu gom riêng", "Bazơ mạnh và nhận biết ion sunfat",
                    "#E9E9E3", 0f, 0.35f, false),
                C("sodium-carbonate", "Natri cacbonat", "Na₂CO₃", ChemicalPhase.Solid, ChemicalModelKind.Powder,
                    105.988, "2,54 g/cm³", "851 °C", "Phân hủy",
                    "Bột hoặc tinh thể trắng", "Tan tốt trong nước; dung dịch có tính bazơ",
                    "Gây kích ứng mắt và da", "Tránh bụi, đậy kín", "Tạo kết tủa cacbonat và chuẩn độ axit",
                    "#EEECE5", 0f, 0.28f, false),
                C("sodium-bicarbonate", "Natri hiđrocacbonat", "NaHCO₃", ChemicalPhase.Solid, ChemicalModelKind.Powder,
                    84.007, "2,20 g/cm³", "Phân hủy từ khoảng 50 °C", "Phân hủy",
                    "Bột trắng", "Khoảng 9,6 g/100 mL H₂O · 20 °C",
                    "Nguy cơ thấp; bụi có thể gây kích ứng", "Giữ khô, tránh axit khi chưa kiểm soát khí", "Điều chế CO₂ và hệ đệm",
                    "#F0EFE9", 0f, 0.26f, false),
                C("calcium-chloride", "Canxi clorua", "CaCl₂", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    110.978, "2,15 g/cm³", "772 °C", "1.935 °C",
                    "Tinh thể trắng, hút ẩm mạnh", "Tan rất nhiều trong nước và tỏa nhiệt",
                    "Gây kích ứng; dung dịch đậm đặc nóng khi pha", "Thêm từ từ vào nước, bảo quản kín", "Nguồn ion Ca²⁺ và chất hút ẩm",
                    "#ECECE6", 0f, 0.34f, false),
                C("copper-chloride", "Đồng(II) clorua đihiđrat", "CuCl₂·2H₂O", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    170.482, "2,51 g/cm³", "Mất nước khoảng 100 °C", "Phân hủy",
                    "Tinh thể xanh lục lam", "Tan tốt trong nước, dung dịch xanh lục",
                    "Có hại và nguy hại môi trường nước", "Đeo găng; thu gom chất thải đồng riêng", "Tạo kết tủa Cu(OH)₂ và phản ứng thế",
                    "#278A78", 0f, 0.40f, false),
                C("iron-sulfate", "Sắt(II) sunfat heptahiđrat", "FeSO₄·7H₂O", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    278.014, "1,90 g/cm³", "Mất nước từ khoảng 64 °C", "Phân hủy",
                    "Tinh thể xanh lục nhạt", "Tan trong nước; dung dịch dễ bị oxi hóa",
                    "Có hại khi nuốt; gây kích ứng", "Đậy kín, chuẩn bị dung dịch mới và thu gom kim loại", "Tạo Fe(OH)₂ và minh họa Fe²⁺/Fe³⁺",
                    "#79A88C", 0f, 0.36f, false),
                C("aluminium-chloride", "Nhôm clorua hexahiđrat", "AlCl₃·6H₂O", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    241.432, "Khoảng 2,4 g/cm³", "Khoảng 100 °C · phân hủy", "Phân hủy",
                    "Tinh thể trắng hoặc không màu, hút ẩm", "Tan mạnh trong nước, dung dịch có tính axit",
                    "Ăn mòn và gây kích ứng", "Tránh ẩm; đeo kính, găng", "Tạo Al(OH)₃ lưỡng tính",
                    "#E9E8E2", 0f, 0.34f, false),
                C("ammonium-chloride", "Amoni clorua", "NH₄Cl", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    53.491, "1,53 g/cm³", "Thăng hoa/phân hủy khoảng 338 °C", "Thăng hoa",
                    "Tinh thể trắng", "Khoảng 37 g/100 mL H₂O · 20 °C",
                    "Gây kích ứng; đun nóng sinh hơi NH₃/HCl", "Tránh hít bụi và gia nhiệt ngoài tủ hút", "Điều chế NH₃ và dung dịch đệm",
                    "#EEEDE7", 0f, 0.34f, false),
                C("sodium-sulfate", "Natri sunfat", "Na₂SO₄", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    142.042, "2,66 g/cm³", "884 °C", "Phân hủy ở nhiệt độ rất cao",
                    "Tinh thể trắng", "Tan trong nước", "Nguy cơ thấp; bụi kích ứng nhẹ",
                    "Giữ khô, tránh tạo bụi", "Nguồn ion SO₄²⁻ để nhận biết Ba²⁺",
                    "#EEEDE7", 0f, 0.34f, false),
                C("potassium-nitrate", "Kali nitrat", "KNO₃", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    101.103, "2,11 g/cm³", "334 °C", "Phân hủy khoảng 400 °C",
                    "Tinh thể trắng", "Độ tan tăng mạnh theo nhiệt độ",
                    "Chất oxi hóa; làm tăng cháy", "Cách xa chất cháy và chất khử", "Muối nitrat và thí nghiệm kết tinh",
                    "#EEEDE7", 0f, 0.35f, false),
                C("sodium-sulfide", "Natri sunfua", "Na₂S", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    78.045, "1,86 g/cm³", "1.176 °C", "Phân hủy",
                    "Tinh thể không màu đến vàng nhạt, hút ẩm", "Tan tốt; dung dịch có tính bazơ",
                    "Ăn mòn; gặp axit sinh H₂S cực độc", "Chỉ thao tác trong tủ hút, tuyệt đối tránh axit ngoài kiểm soát", "Nhận biết ion kim loại bằng kết tủa sunfua",
                    "#E2D38B", 0f, 0.32f, false),
                C("aluminium", "Nhôm", "Al", ChemicalPhase.Solid, ChemicalModelKind.Metal,
                    26.982, "2,70 g/cm³", "660,3 °C", "2.470 °C",
                    "Kim loại trắng bạc", "Không tan trong nước; tan trong axit/kiềm khi phá màng oxit",
                    "Bột mịn dễ cháy; phản ứng thế có thể tỏa nhiệt", "Dùng mảnh kim loại, tránh bột", "Minh họa tính lưỡng tính và phản ứng thế",
                    "#C9CED1", 0.88f, 0.75f, false),
                C("iron", "Sắt", "Fe", ChemicalPhase.Solid, ChemicalModelKind.Metal,
                    55.845, "7,87 g/cm³", "1.538 °C", "2.862 °C",
                    "Kim loại xám bạc", "Không tan trong nước; tan trong axit loãng",
                    "Bột sắt dễ cháy; axit có thể giải phóng H₂", "Dùng đinh hoặc mảnh sắt sạch", "Phản ứng thế và dãy hoạt động kim loại",
                    "#7E8588", 0.84f, 0.61f, false),
                C("sodium-phosphate", "Natri photphat", "Na₃PO₄", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    163.940, "2,54 g/cm³", "1.340 °C", "Phân hủy",
                    "Tinh thể trắng", "Tan trong nước; dung dịch có tính bazơ",
                    "Gây kích ứng và có thể gây bỏng mắt", "Đeo kính, tránh bụi", "Nguồn ion PO₄³⁻ để tạo kết tủa",
                    "#EEEDE7", 0f, 0.34f, false),
                C("calcium-oxide", "Canxi oxit", "CaO", ChemicalPhase.Solid, ChemicalModelKind.Powder,
                    56.077, "3,34 g/cm³", "2.572 °C", "2.850 °C",
                    "Chất rắn trắng hoặc xám nhạt", "Phản ứng với nước tạo Ca(OH)₂",
                    "Ăn mòn; phản ứng với nước tỏa nhiệt mạnh", "Thêm lượng nhỏ vào nước sau tấm chắn", "Minh họa oxit bazơ và phản ứng tôi vôi",
                    "#E5E3DA", 0f, 0.24f, false),
                C("potassium-bromide", "Kali bromua", "KBr", ChemicalPhase.Solid, ChemicalModelKind.Crystals,
                    119.002, "2,75 g/cm³", "734 °C", "1.435 °C",
                    "Tinh thể trắng", "Tan tốt trong nước",
                    "Nguy cơ thấp ở lượng thí nghiệm", "Giữ khô, tránh chất oxi hóa mạnh", "Nhận biết Br⁻ bằng AgNO₃",
                    "#ECEBE4", 0f, 0.35f, false)
            };
        }

        public static IEnumerable<ReactionDefinition> BuildReactions()
        {
            return new[]
            {
                R("sulfuric-neutralization", "Trung hòa axit sunfuric", "sulfuric-acid", 1d, "sodium-hydroxide", 2d,
                    "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O", "Na₂SO₄", 142.042, .97f, ReactionEffect.Heat, "#E4EEEC", 13f, false,
                    "Dung dịch nóng lên rõ rệt, không tạo kết tủa.", "Làm nguội và kiểm tra pH trước khi xử lý."),
                R("nitric-potassium-neutralization", "Trung hòa axit nitric", "nitric-acid", 1d, "potassium-hydroxide", 1d,
                    "HNO₃ + KOH → KNO₃ + H₂O", "KNO₃", 101.103, .97f, ReactionEffect.Heat, "#E7EFEC", 10f, false,
                    "Dung dịch nóng lên; tạo dung dịch kali nitrat không màu.", "Đưa pH về trung tính, giữ xa chất hữu cơ nếu còn nitrat đậm đặc."),
                R("phosphoric-neutralization", "Trung hòa hoàn toàn axit photphoric", "phosphoric-acid", 1d, "sodium-hydroxide", 3d,
                    "H₃PO₄ + 3NaOH → Na₃PO₄ + 3H₂O", "Na₃PO₄", 163.940, .94f, ReactionEffect.Heat, "#E7EFEC", 7f, false,
                    "Dung dịch ấm lên; sản phẩm phụ thuộc tỉ lệ mol bazơ/axit.", "Kiểm tra pH vì photphat có thể làm dung dịch còn tính bazơ."),
                R("hydrochloric-calcium-neutralization", "Trung hòa bằng canxi hiđroxit", "hydrochloric-acid", 2d, "calcium-hydroxide", 1d,
                    "2HCl + Ca(OH)₂ → CaCl₂ + 2H₂O", "CaCl₂", 110.978, .94f, ReactionEffect.Heat, "#E6EFEC", 8f, false,
                    "Huyền phù trắng tan dần, nhiệt độ tăng.", "Kiểm tra pH và lọc phần Ca(OH)₂ dư nếu có."),
                R("barium-complete-neutralization", "Trung hòa và kết tủa bari sunfat", "sulfuric-acid", 1d, "barium-hydroxide", 1d,
                    "H₂SO₄ + Ba(OH)₂ → BaSO₄↓ + 2H₂O", "BaSO₄", 233.389, .96f, ReactionEffect.Precipitate, "#EEEDE7", 9f, false,
                    "Xuất hiện kết tủa trắng đồng thời dung dịch nóng lên.", "Mọi chất thải bari phải thu gom trong bình độc chất."),
                R("acetic-potassium-neutralization", "Trung hòa axit axetic bằng KOH", "acetic-acid", 1d, "potassium-hydroxide", 1d,
                    "CH₃COOH + KOH → CH₃COOK + H₂O", "CH₃COOK", 98.143, .95f, ReactionEffect.Heat, "#E7EEEA", 5f, false,
                    "Dung dịch ấm nhẹ và mùi giấm giảm.", "Kiểm tra pH trước khi xử lý."),
                R("copper-chloride-hydroxide", "Kết tủa đồng(II) hiđroxit", "copper-chloride", 1d, "sodium-hydroxide", 2d,
                    "CuCl₂ + 2NaOH → Cu(OH)₂↓ + 2NaCl", "Cu(OH)₂", 97.561, .93f, ReactionEffect.Precipitate, "#3FA6CE", 1f, false,
                    "Kết tủa xanh lam dạng keo xuất hiện.", "Thu gom vào bình chất thải đồng."),
                R("iron-two-hydroxide", "Kết tủa sắt(II) hiđroxit", "iron-sulfate", 1d, "sodium-hydroxide", 2d,
                    "FeSO₄ + 2NaOH → Fe(OH)₂↓ + Na₂SO₄", "Fe(OH)₂", 89.860, .90f, ReactionEffect.Precipitate, "#789A74", .8f, false,
                    "Kết tủa lục nhạt tạo thành rồi nâu dần do oxi hóa trong không khí.", "Thu gom chất thải sắt; không đổ huyền phù vào bồn."),
                R("aluminium-hydroxide", "Kết tủa nhôm hiđroxit", "aluminium-chloride", 1d, "sodium-hydroxide", 3d,
                    "AlCl₃ + 3NaOH → Al(OH)₃↓ + 3NaCl", "Al(OH)₃", 78.004, .92f, ReactionEffect.Precipitate, "#EEEDE8", .9f, false,
                    "Kết tủa trắng keo; tan lại khi NaOH dư nhiều do tính lưỡng tính.", "Kiểm tra lượng bazơ dư, thu gom huyền phù."),
                R("calcium-carbonate-precipitation", "Kết tủa canxi cacbonat", "calcium-chloride", 1d, "sodium-carbonate", 1d,
                    "CaCl₂ + Na₂CO₃ → CaCO₃↓ + 2NaCl", "CaCO₃", 100.087, .96f, ReactionEffect.Precipitate, "#EEEDE8", .4f, false,
                    "Kết tủa trắng mịn xuất hiện nhanh.", "Lọc chất rắn; dung dịch sau lọc được xử lý theo quy trình muối."),
                R("copper-carbonate-precipitation", "Kết tủa cacbonat đồng(II)", "copper-sulfate", 1d, "sodium-carbonate", 1d,
                    "CuSO₄ + Na₂CO₃ → CuCO₃↓ + Na₂SO₄", "CuCO₃", 123.555, .90f, ReactionEffect.Precipitate, "#4C9D80", .8f, false,
                    "Kết tủa xanh lục lam hình thành; thực tế có thể là cacbonat bazơ.", "Thu gom toàn bộ chất rắn chứa đồng."),
                R("silver-iodide", "Bạc iodua", "silver-nitrate", 1d, "potassium-iodide", 1d,
                    "AgNO₃ + KI → AgI↓ + KNO₃", "AgI", 234.773, .95f, ReactionEffect.Precipitate, "#E3D04F", .3f, false,
                    "Kết tủa vàng nhạt, không tan trong dung dịch amoniac loãng.", "Thu gom riêng chất thải bạc."),
                R("silver-bromide", "Bạc bromua", "silver-nitrate", 1d, "potassium-bromide", 1d,
                    "AgNO₃ + KBr → AgBr↓ + KNO₃", "AgBr", 187.772, .95f, ReactionEffect.Precipitate, "#E7D9A3", .3f, false,
                    "Kết tủa vàng kem, sẫm màu dần dưới ánh sáng.", "Thu gom riêng chất thải bạc."),
                R("barium-sodium-sulfate", "Nhận biết ion sunfat", "barium-chloride", 1d, "sodium-sulfate", 1d,
                    "BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl", "BaSO₄", 233.389, .97f, ReactionEffect.Precipitate, "#EEEDE7", .4f, false,
                    "Kết tủa trắng BaSO₄ rất ít tan.", "Giữ toàn bộ chất thải bari trong bình chuyên dụng."),
                R("iron-phosphate", "Kết tủa sắt(III) photphat", "iron-chloride", 1d, "sodium-phosphate", 1d,
                    "FeCl₃ + Na₃PO₄ → FePO₄↓ + 3NaCl", "FePO₄", 150.817, .91f, ReactionEffect.Precipitate, "#D4C589", .7f, false,
                    "Xuất hiện kết tủa vàng nhạt đến vàng nâu.", "Thu gom huyền phù kim loại."),
                R("carbonate-hydrochloric", "Axit tác dụng với muối cacbonat", "sodium-carbonate", 1d, "hydrochloric-acid", 2d,
                    "Na₂CO₃ + 2HCl → 2NaCl + CO₂↑ + H₂O", "CO₂", 44.009, .94f, ReactionEffect.Gas, "#DDEBEC", 2f, true,
                    "Sủi bọt CO₂ mạnh, dung dịch trong dần.", "Dùng tủ hút và không đậy kín bình phản ứng."),
                R("bicarbonate-hydrochloric", "Axit tác dụng với hiđrocacbonat", "sodium-bicarbonate", 1d, "hydrochloric-acid", 1d,
                    "NaHCO₃ + HCl → NaCl + CO₂↑ + H₂O", "CO₂", 44.009, .96f, ReactionEffect.Gas, "#DDEBEC", 1f, true,
                    "Sủi bọt CO₂ đều và chất rắn tan.", "Dùng tủ hút; không đóng kín dụng cụ sinh khí."),
                R("carbonate-sulfuric", "Axit sunfuric và natri cacbonat", "sodium-carbonate", 1d, "sulfuric-acid", 1d,
                    "Na₂CO₃ + H₂SO₄ → Na₂SO₄ + CO₂↑ + H₂O", "CO₂", 44.009, .93f, ReactionEffect.Gas, "#DDEBEC", 4f, true,
                    "Sủi bọt CO₂ và hỗn hợp ấm lên.", "Thao tác trong tủ hút; pha loãng axit trước."),
                R("sulfide-acid", "Giải phóng hiđro sunfua", "sodium-sulfide", 1d, "hydrochloric-acid", 2d,
                    "Na₂S + 2HCl → 2NaCl + H₂S↑", "H₂S", 34.081, .88f, ReactionEffect.Gas, "#D8DFCA", 2f, true,
                    "Sinh H₂S không màu, cực độc; mô phỏng khóa ngoài tủ hút.", "Xả qua hệ hấp thụ của tủ hút; tuyệt đối không ngửi."),
                R("iron-copper-displacement", "Sắt đẩy đồng khỏi muối", "iron", 1d, "copper-sulfate", 1d,
                    "Fe + CuSO₄ → FeSO₄ + Cu↓", "Cu", 63.546, .90f, ReactionEffect.Colour, "#B9673D", 2f, false,
                    "Đồng đỏ bám lên sắt; màu xanh dung dịch nhạt dần và ngả lục.", "Thu gom dung dịch sắt–đồng vào chất thải kim loại."),
                R("zinc-copper-displacement", "Kẽm đẩy đồng khỏi muối", "zinc", 1d, "copper-sulfate", 1d,
                    "Zn + CuSO₄ → ZnSO₄ + Cu↓", "Cu", 63.546, .92f, ReactionEffect.Colour, "#B9673D", 4f, false,
                    "Đồng đỏ nâu bám trên kẽm, dung dịch xanh nhạt dần.", "Thu gom kim loại và dung dịch chứa đồng riêng."),
                R("aluminium-copper-displacement", "Nhôm đẩy đồng khỏi muối", "aluminium", 2d, "copper-chloride", 3d,
                    "2Al + 3CuCl₂ → 2AlCl₃ + 3Cu↓", "3Cu", 190.638, .86f, ReactionEffect.Heat, "#B9673D", 16f, false,
                    "Sau khi phá màng oxit, đồng đỏ bám nhanh và hỗn hợp nóng lên.", "Dùng lượng nhỏ sau tấm chắn; để nguội trước khi thu gom."),
                R("ammonium-base", "Điều chế amoniac từ muối amoni", "ammonium-chloride", 1d, "sodium-hydroxide", 1d,
                    "NH₄Cl + NaOH → NaCl + NH₃↑ + H₂O", "NH₃", 17.031, .90f, ReactionEffect.Gas, "#DCE9EC", 5f, true,
                    "Khí NH₃ không màu sinh ra; không được kiểm tra mùi trực tiếp.", "Chỉ thực hiện trong tủ hút và hấp thụ khí dư vào dung dịch axit loãng."),
                R("quicklime-water", "Tôi vôi", "calcium-oxide", 1d, "water", 1d,
                    "CaO + H₂O → Ca(OH)₂", "Ca(OH)₂", 74.093, .95f, ReactionEffect.Heat, "#EEEDE8", 28f, false,
                    "Chất rắn nở, tạo huyền phù trắng và tỏa nhiệt mạnh.", "Dùng kính, găng; để nguội hoàn toàn trước khi xử lý."),
                R("carbonate-nitric", "Axit nitric và canxi cacbonat", "calcium-carbonate", 1d, "nitric-acid", 2d,
                    "CaCO₃ + 2HNO₃ → Ca(NO₃)₂ + CO₂↑ + H₂O", "CO₂", 44.009, .90f, ReactionEffect.Gas, "#DDEBEC", 3f, true,
                    "Sủi bọt CO₂ và chất rắn tan dần.", "Thao tác trong tủ hút; dung dịch nitrat phải thu gom riêng.")
            };
        }

        private static ChemicalDefinition C(
            string id,
            string name,
            string formula,
            ChemicalPhase phase,
            ChemicalModelKind kind,
            double molarMass,
            string density,
            string melting,
            string boiling,
            string appearance,
            string solubility,
            string hazards,
            string handling,
            string use,
            string colour,
            float metallic,
            float smoothness,
            bool transparent)
        {
            return new ChemicalDefinition(
                id, name, formula, phase, kind, molarMass, density, melting, boiling,
                appearance, solubility, hazards, handling, use, colour, metallic, smoothness, transparent);
        }

        private static ReactionDefinition R(
            string id,
            string name,
            string reactantA,
            double coefficientA,
            string reactantB,
            double coefficientB,
            string equation,
            string product,
            double productMass,
            float yieldFraction,
            ReactionEffect effect,
            string colour,
            float temperature,
            bool hood,
            string observation,
            string disposal)
        {
            return new ReactionDefinition(
                id, name, reactantA, coefficientA, reactantB, coefficientB, equation,
                product, productMass, yieldFraction, effect, colour, temperature, hood, observation, disposal);
        }
    }
}
